name: "Sam's Hams"
favicon: null
layout_spectrum: 0.25361
typography_spectrum: 0.75542
title: "Sam's Hams"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f05657'
    - '#fff3d9'
    - '#f8a99c'
    - '#fbcbb8'
    - '#f2736f'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
